version: '3'

tasks:
  filtr:
    desc: Compile filtr.tex to pdf
    sources:
      - src/filtr/*
      - mystd.sty
    cmds:
      - tectonic "./src/filtr/filtr.tex" -Z search-path="." --outdir "pdf" --synctex
  fft:
    desc: Compile fft.tex to pdf
    sources:
      - src/fft/*
      - mystd.sty
    cmds:
      - tectonic "./src/fft/fft.tex" -Z search-path="." --outdir "pdf" --synctex
  algebra:
    desc: Compile algebra.tex to pdf
    sources:
      - src/algebra/*
      - mystd.sty
    cmds:
      - tectonic "./src/algebra/algebra.tex" -Z search-path="." --outdir "pdf" --synctex
  analiza:
    desc: Compile analiza.tex to pdf
    sources:
      - src/analiza/*
      - mystd.sty
    cmds:
      - tectonic "./src/analiza/analiza.tex" -Z search-path="." --outdir "pdf" --synctex