version: '3'

tasks:
  filtr:
    desc: Compile filtr.tex to pdf
    sources:
      - src/filtr/*
      - mystd.sty
    cmds:
      - cd src/filtr && arara filtr.tex
      - cd pdf && rm -f *.aux *.log *.out *.synctex.gz *.toc *.fls *.fdb_latexmk
  fft:
    desc: Compile fft.tex to pdf
    sources:
      - src/fft/*
      - mystd.sty
    cmds:
      - cd src/fft && arara fft.tex
      - cd pdf && rm -f *.aux *.log *.out *.synctex.gz *.toc *.fls *.fdb_latexmk
  algebra:
    desc: Compile algebra.tex to pdf
    sources:
      - src/algebra/*
      - mystd.sty
    cmds:
      - cd src/algebra && arara algebra.tex
      - cd pdf && rm -f *.aux *.log *.out *.synctex.gz *.toc *.fls *.fdb_latexmk
  analiza:
    desc: Compile analiza.tex to pdf
    sources:
      - src/analiza/*
      - mystd.sty
    cmds:
      - cd src/analiza && arara analiza.tex
      - cd pdf && rm -f *.aux *.log *.out *.synctex.gz *.toc *.fls *.fdb_latexmk