name: CI
on:
  push:
    branches:
    - main
    paths:
    - '**.tex'
    - '**.sty'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Cache tectonic files
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Compile all LaTeX documents
        run:  task filtr fft algebra analiza
